- lib/gtag.ts
- package.json
- pages/_app.tsx
- pages/api/auth/[...auth0].ts
- yarn.lock
Set the account name in the google analytics session [uid](https://developers.google.com/analytics/devguides/collection/ga4/reference/config#user_id) shared parameter. It will be included in subsequent events. 
Relevant info on using this information: https://support.google.com/analytics/answer/9213390
Also in this PR:
- Simple, opt-in cookie-consent banner.
- Pull out the krunchdata and missivechat scripts since we don't use them.
Regardig the large diff, there seems to have been a change in formatting standard for yarn.lock. This one was compiled with yarn `1.22.15`, but it seems to be the same for `1.22.19` which is the latest stable, except that uses the yarnpkg repository rather than npm? TLDR: I miss cargo.
> feat: add user id to google analytics session

- lib/gtag.ts
- pages/_app.tsx
- pages/api/auth/[...auth0].ts
The login was broken by setting the gtag in the auth callback, since window was undefined. This sets in a global useffect instead, where the window should be defined.
> fix: broken login

- lib/gtag.ts
- pages/_app.tsx
Set analytics cookies to opt-out by default in non-gdpr countries and add a decline button. Deny `ad_storage` for everyone by default.
> feat: region specific GA settings

- .gitignore
- components/sections/GetStarted.tsx
- components/sections/HowItWorks.tsx
- pages/dashboard/index.tsx
Fix these buttons so they copy the command to the clipboard
> fix: copy buttons on main page should copy to clipboard

- _blog/2023-03-01-getting-started-with-rust-and-gpt.mdx
Hello,
I found a typo in the code snippet that introduces the route handler function. The comment line at the top was incorrect.  I also updated the discussion of the dependencies to show reference to version 0.13 instead of 0.12.
I updated the companion repo and opened a PR for Josh to review.
Cheers,
~Jeff Mitchell
> Update for Shuttle 0.13, fix typo API route

- _blog/2023-08-23-rust-web-framework-comparison.mdx
- "Actix" -> "Actix Web" unless referring to the actor library
- Actix Web is not based on actors
> docs: fix errors in Actix Web comparison

- pages/launchpad/issues/[slug].tsx
> fix: correctly copy `::` in code examples 

- content/jobs.ts
The job position doesn't exist anymore
> refactor: Remove Rust mid engineer job position

- _blog/2023-09-20-logging-in-rust.mdx
The blog post originally used the log and tracing crates like this:
```rust
use log::warn;
warn!("message");
```
However, that is considered a code smell because when reading through a codebase it is not obvious which crate is being used i.e. is it `log::warn`? or `tracing::warn`? or something custom? that is not obvious from the code at all.
With macro and function names that are as ubiquitous as e.g. `debug` it's good practice to include the crate first even if it is a bit more verbose.
```rust
use log;
// a hundred lines further down...
log::debug!("me"); // it's clear which logging system we use
```
Edit: I know this is taken from the `tracing` and `log` doc.rs pages, but that should really be updated, `tracing` uses the clearer `tracing::<macro>` style within all their other examples
> Rust logging blog post: Idiomatic usage of log and tracing crates

- _blog/2023-10-04-sql-in-rust.mdx
- SQLx isn't supporting MSSQL post 0.7
- Inconsistency ("chan0" vs "testNotify")
> fix: errata

- pages/blog/[year]/[month]/[day]/[slug].tsx
Right now the share button assumes that the Mastodon instance you want to share the article on is `mastodon.social`.   
The PR prompts the user (using the naive `window.prompt` method) to ask the user which instance they want to share the post to.
> feat: Modify Mastodon Share button to work with arbitrary instances

- _launchpad/2023-10-17-issue-10-Serving-HTML.mdx
Removes the part where we talk about being at EuroRust, because it's already too far in the future.
> refactor: We're not at EuroRust anymore

- _launchpad/2023-03-07-issue-03-Ownership-Error-Handling.mdx
- _launchpad/2023-06-16-issue-01-Getting-Started.mdx
- _launchpad/2023-06-16-issue-02-Structs-and-Enums.mdx
- _launchpad/2023-07-14-issue-04-Ownership-Lifetimes.mdx
- _launchpad/2023-10-17-issue-10-Serving-HTML.mdx
- _launchpad/2023-11-08-issue-06-CRUD-Postgres.mdx
- _launchpad/2023-12-09-issue-08-websockets-chat.mdx
- _launchpad/2023-17-11-issue-11-12-testing-axum-applications.mdx
- _launchpad/2023-22-09-issue-09-custom-validation.mdx
- _launchpad/2023-28-07-issue-05-Traits-Image-Processing.mdx
- _launchpad/2023-28-08-issue-07-more-CRUD.mdx
- components/sections/ShuttleAI/Waitlist.tsx
- components/sections/ShuttleBatch/Countdown.tsx
- components/sections/ShuttleBatch/Testimonials.tsx
- components/sections/ShuttleHeroesHero.tsx
- lib/constants.ts
I applied to be a Shuttle Hero earlier and noticed that the typeform URL had a redirect. I changed it to the new URL it recommended. Since I already cloned the repo earlier thought i'd change it over! I also decided to take a look and change the other URLs I could find. I don't know if they're still in use, but I wanted to grab them. Also, my IDE did some whitespace changes, and Lint didn't fix it. If I need to, I can go back and edit those out. Thanks!
> Updated the typeform urls

- components/elements/Starter.tsx
I noticed when browsing the homepage of the website that the Deploy links don't work - i.e. they 404. This is due to `deployLink` being falsy, and the fallback of `/login` is incorrect as it's not pointing to the `console.shuttle.rs` domain.
> fix: incorrect fallback link for starter deploy

- _blog/2024-04-29-building-your-first-ai-tool-rust.mdx
`llm-chain` requires environment variables, not `dotenvy`.
> fix: correct the "AI first tool" article

- _blog/2024-05-30-semantic-caching-qdrant-rust.mdx
Amends a code snippet to include score threshold as required for `ScorePoints`.
> fix: article wording

- _blog/2024-03-13-simple-web-server-rust.mdx
I was going through the https://www.shuttle.rs/blog/2024/03/13/simple-web-server-rust blog post and ran into a few issues, which I've fixed in this PR.
I also ran into an incompatibility between the latest version of SQLx and shuttle-shared-db, which I fixed by downgrading SQLx to version 0.7.1.
> Simple web server blog fixes

- components/sections/CallToActionNewsletter.tsx
- components/sections/index.tsx
- next-env.d.ts
- pages/blog/[year]/[month]/[day]/[slug].tsx
- pages/blog/tags/[tag].tsx
Added a component for the newsletter which we are implementing for the blog. The newsletter itself is setup on button down already, we just need to add relevant and non-intrusive CTAs to the blog. At the moment we've added one at the top of a blog post and one at the bottom. This should be enough in my opinion, but we may want to add one to the tags page as well.
There is a bug where the input is not responsive if the background image is used - this is for the input at the bottom of the post.
> feat: added newsletter cta component to [slug] page

- pages/index.tsx
Comments out the anti-scam banner.
It hasn't been outright removed as we may need it in the future if the job offer scams start appearing again.
> refactor: remove anti-scam banner

- _blog/2024-08-23-rust-as-my-first-language.mdx
Hey guys,
Have pulled my jeff-mitchell.dev blog out of production for the time being. I'm kind of re-visiting/re-homing the whole thing.
Perhaps I'll just shelve it and write directly for Shuttle more often :)
It's difficult to stay interested in writing when no one reads it.
Anyways, doing a pull request to update the "Rust as my First Language Article", didn't want broken links.
~Jeff
> chore: remove link to blog at the end of the post

- _blog/2024-11-29-the-essence-of-templating-with-tera.mdx
Hey guys, 
Same deal with this post, took out the shameless self-promotion, as it doesn't exist anymore.
I wrote a new, short introduction for the article.
~Jeff
> chore: remove blog link in introduction of the article

- next.config.js
There was a conflict between i18n settings and
path matching rules for the header overrides.
Part of PLA-338
> fix: apply header overrides to the root URI too

- _blog/2023-04-14-Shuttle-Batch-2.mdx
- _blog/2024-01-22-introducing-shuttlebytes.mdx
- _blog/2024-10-10-shuttle-redefining-backend-development.mdx
- _blog/2025-09-09-ai-coding-tools-rust.mdx
- _blog/2025-09-15-mcp-servers-rust-comparison.mdx
- components/blog/TableOfContents.tsx
- components/sections/BlogSidebar.tsx
- components/sections/SidebarTOC.tsx
- pages/blog/[year]/[month]/[day]/[slug].tsx
This PR creates table of contents section (called `On this page`) in the blog post sidebar in a form of a tree with infinite depth levels, to support sub-headers within the content.
The currently active section is highlighted while scrolling. Max depth level is set to 3 (h3).
> feat: Add `On this page` in `BlogSidebar` (TOC)
