shuttle-hq/www

lib/gtag.ts
pages/api/auth/[...auth0].ts

Set the correct user id in gtag.

fix: set account name aka user id in gtag

---

_blog/2023-03-01-getting-started-with-rust-and-gpt.mdx

I've taken a stab at updating the Rust code snippets in the original blog post, to reflect the version 0.12 changes.  The code in the associated GitHub repo still needs to be changed.  I figured the original author would probably want to work on that.
Cheers,
~Jeff Mitchell

Updated Rust code snippets to reflect version 0.12

---

components/sections/DashboardNavigation.tsx
components/sections/Footer.tsx

Fix broken docs link in Footer and Dashboard nav; fix discord link in Dashboard nav

---

_blog/2022-08-04-middleware.mdx

Good morning,
In reading through the "Middleware" blog post, I noticed some minor typos, which this PR fixes. I also made some small wording changes to improve readability.
~Jeff Mitchell

Correct minor typos and improve readability

---

components/templates/DashboardPage.tsx

Fix: Dashboard Refresh

---

_blog/2022-08-11-authentication-tutorial.mdx
_blog/2022-09-14-serenity-discord-bot.mdx
_launchpad/2023-06-16-issue-01-Getting-Started.mdx

This is just a simple update to align the documentation with the latest syntax

Update example to use correct newer cargo shuttle project start syntax

---

components/sections/HowItWorks.tsx
components/sections/Mission.tsx
components/sections/Pricing.tsx
components/sections/ShuttleHeroesHero.tsx
components/sections/ShuttleHeroesResponsibilities.tsx
pages/dashboard/index.tsx

- Capitalises Shuttle.
I tried to find instances where alpha should be changed to beta but couldn't really find anything applicable on this repo.

docs: capitalise Shuttle

---

components/sections/Footer.tsx
pages/contact.tsx

Adds a contact page with a simple form for users to reach out to Shuttle team.

feat: contact page

---

components/elements/Button.tsx
components/sections/Navigation/index.tsx

fix: dashboard -> console

---

_launchpad/2023-12-09-issue-08-websockets-chat.mdx

fix: typo in shuttle #8 javascript

---

components/elements/Button.tsx
components/sections/Pricing.tsx
components/sections/Pricing/BenefitsCards.tsx
components/sections/Pricing/Calculator.tsx
components/sections/Pricing/LovedBy.tsx
components/sections/Pricing/PriceCards.tsx
components/sections/StarOnGithub.tsx
content/faq.ts
content/plans.ts
lib/shuttle.ts
package-lock.json
pages/_app.tsx

Currently contains:
- vCPU & RAM slider at the top and combined, with only the price box below
- Many other changes. (please take a good look at the preview deployment)

fix: pricing page corrections and fixes

---

_blog/2023-10-16-graphql-in-rust.mdx

fix: new article date

---

_blog/2023-10-25-htmx-with-rust.mdx

fix: hotfix amendments

---

components/sections/ShuttleAI/Hero.tsx

Fixes the broken URLs for the Shuttle AI page

fix: broken URL

---

_blog/2022-03-13-url-shortener.mdx

Evening guys,
I've updated the blog version of the url-shortener article, to make it consistent with the docs version.
~Jeff

improvement: update url-shortener for rocket rc.4

---

_blog/2023-12-08-clap-rust.mdx

todo:
- ~~SEO/promo plans (currently being sorted at the moment)~~ done
- ~~amend frontmatter (the bit at the top)~~ done
- thumbnail (will merge without - thumbnail to be created later on and added)

feat: clap article

---

_blog/2023-12-15-using-actix-rust.mdx

todo:
- Thumbnail
- ~~SEO/Promo plan (being worked on)~~
- ~~Frontmatter~~

feat: actix article

---

_blog/2023-12-06-using-axum-rust.mdx

Some corrections are required as it was discovered that this code is not quite correct.

refactor: article code corrections

---

_blog/2023-12-06-using-axum-rust.mdx

fix: axum blog post code formatting

---

next.config.js

feat: add install-win script redirect

---

_blog/2023-12-06-using-axum-rust.mdx

Corrects some code snippets in the Axum article.

fix: code corrections

---

_blog/2023-10-04-sql-in-rust.mdx
_blog/2023-10-16-graphql-in-rust.mdx
components/sections/Pricing.tsx
components/sections/Pricing/PriceCards.tsx
content/plans.ts

RDS will be a paid add-on instead

misc: updated references of RDS as a pro-tier add-on

---

components/sections/Navigation/index.tsx

fix: sidebar closing on link click

---

_blog/2024-03-06-writing-wasm-rust.mdx

Fixes a code language annotation.

refactor: code syntax

---

_blog/2023-12-08-clap-rust.mdx

Fixes inconsistencies in the clap article.

fix: clap article consistency

---

prettier.config.js

refactor: remove deprecated `prettier` property

---

_blog/2023-10-25-htmx-with-rust.mdx

Updates the GitHub link to our official example.

feat: update htmx article repo link

---

pages/ai.tsx

Changes the video src to the new youtube video.
(to be superceded by cdn)

feat: ai page vidsrc

---

next.config.js

Removing the login redirect as it does nothing for SEO and doesn't show any image tags via OpenGraph which makes it somewhat pointless.

refactor: Remove login redirect

---

components/sections/Pricing.tsx
content/plans.ts

This reverts commit b379ebc3326256bd07201157f945cc21c1194bfc.

Revert "feat: update account tier project limits (#362)"

---

_blog/2024-10-22-using-kubernetes-with-rust.mdx
components/blog/TableOfContents.tsx
components/sections/BlogSidebar.tsx
lib/blog/posts.ts
pages/blog/[year]/[month]/[day]/[slug].tsx

- Table of contents is now on the main part of the blog pages
- Correctly displays h1/h2/h3

feat: table of contents improvements

---

lib/blog/authors.ts
pages/cch.tsx

- Updates Christos' blog author image
- Adds Shuttle NextSEO stuff to the CCH page

fix: update authors

---

_blog/2022-06-09-the-builder-pattern.mdx
_blog/2022-06-16-a-short-introduction-to-async-rust.mdx
_blog/2022-08-04-middleware-in-rust.mdx
_blog/2023-09-08-building-semantic-search-in-rust.mdx
_blog/2023-09-27-rust-vs-go-comparison.mdx
_blog/2023-10-16-graphql-in-rust.mdx
_blog/2024-03-06-writing-wasm-rust.mdx
_blog/2024-03-27-datadog-rust.mdx
_blog/2024-04-04-using-openapi-rust.mdx
_launchpad/2023-06-16-issue-01-Getting-Started.mdx
_launchpad/2023-10-21-issue-11-refactoring.mdx
pages/terms.tsx

Fixes broken links as well as adding SEO-friendly links in place of unfriendly ones

fix: broken links

---

pages/cch.tsx
pages/launchpad/issues/[slug].tsx

Fixes SEO meta descriptions on Launchpad and the CCH page.

fix: SEO meta descriptions

---

components/sections/Navigation/index.tsx
styles/globals.css

Added the hightlight for the nav-links so the user gets to know what page they are on. 
Before:
After:

highlight for the navlinks
